require "options"
require "keymaps"
require "functions"
require "autocmds"

require "plugins"
require "plugins.impatient"
-- require "plugins.indent-blankline"
-- require "plugins.treesitter"
require "plugins.cmp"
require "plugins.alpha"
require "plugins.surround"
require "plugins.nvim-tree"
require "plugins.neoscroll"
require "plugins.colorscheme"
require "plugins.bufferline"
require "plugins.lualine"
require "plugins.gitsigns"
require "plugins.toggleterm"
require "plugins.comment"

require "plugins.which-key"
